{"name": "test_div[除数是0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 'division by zero'\n  +None\n  -'division by zero'", "trace": "self = <testcode.test_calc_new.Test_Calculator object at 0x000001B30DF53E20>\nget_calc = <pythoncode.Calculator.Calculator object at 0x000001B30DF53190>, get_div_datas = [1, 0, 'division by zero']\n\n    @pytest.mark.run(order=4)\n    def test_div(self, get_calc, get_div_datas):\n        res = None\n        try:\n            res = get_calc.div(get_div_datas[0], get_div_datas[1])\n            if isinstance(res, float):\n                res = round(res, 2)\n            print(f'计算结果为：{res}')\n        except Exception as e:\n            print(e)\n>       assert res == get_div_datas[2]\nE       AssertionError: assert None == 'division by zero'\nE         +None\nE         -'division by zero'\n\ntest_calc_new.py:34: AssertionError"}, "parameters": [{"name": "get_div_datas", "value": "[1, 0, 'division by zero']"}], "start": 1613319483989, "stop": 1613319483989, "uuid": "1794bfe8-14c0-41ee-9053-3b56b568ce43", "historyId": "f1436e3a4c561ef2e6280bb8b9ce4848", "testCaseId": "c839c0b7efb7e833b1464aab293175a3", "fullName": "testcode.test_calc_new.Test_Calculator#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "parentSuite", "value": "testcode"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "Test_Calculator"}, {"name": "host", "value": "LAPTOP-K9V7IUFS"}, {"name": "thread", "value": "3596-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcode.test_calc_new"}]}